In [1]:
import TTest as main
import numpy as np
import Picture.calculateW as calc

data = main.ReadData(10000)
def GetRealY(index):
    list = []
    for i in data[1]:
        list.append(i[index])
    list = np.array(list)
    return list


x = np.array(data[0])
z = calc.GetYProd(np.array(data[0]), np.array([1] * len(data[0][0])), 1)



0
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1

In [3]:
def GradientNew(x, y, w, b):
  yCalc = calc.GetYProd(x, w, b)
  bG = (yCalc - y).mean()
  wG = np.zeros(x.shape[1])
  for i in range(x.shape[1]):
    wG[i] = (x[:, i] * (yCalc - y)).mean()
  return wG, bG

def GradientRunNew(x, maxNum, learningRate, col):
  y = GetRealY(col)
  initW = np.array([0.0] * len(data[0][0]))
  initB = 0
  costBack = -1
  for i in range(maxNum):
    stepW, stepB = GradientNew(x, y, np.array([1] * len(data[0][0])), initB)
    initW -= learningRate * stepW
    initB -= learningRate * stepB
    yCalc = calc.GetYProd(x, initW, initB)
    cost = calc.CalcDistance(y, yCalc)
    if(i % 100 == 0):
      print(f"Running, {i/maxNum * 100:.2f}%, cost: {cost}")
    if(costBack < 0 or costBack > cost):
      costBack = cost
    elif(costBack <= cost):
      print("over")
      return initW + learningRate * stepW, initB + learningRate * stepB

  return initW, initB



In [12]:
def GradientRunNew(x, maxNum, learningRateNum, col):
  learningRate = 1
  y = GetRealY(col)
  initW = np.array([0.0] * len(data[0][0]))
  initB = 0
  costBack = -1
  for i in range(maxNum):
    stepW, stepB = GradientNew(x, y, np.array([1] * len(data[0][0])), initB)
    initW -= learningRate * stepW
    initB -= learningRate * stepB
    yCalc = calc.GetYProd(x, initW, initB)
    cost = calc.CalcDistance(y, yCalc)
    if(i % 100 == 0):
      print(f"Running, {i/maxNum * 100:.2f}%, cost: {cost}")
    if(costBack < 0 or costBack > cost):
      costBack = cost
    elif(costBack <= cost):
      print("reverse")
      print(f"Running, {i/maxNum * 100:.2f}%, cost: {cost}")
      learningRate /= 10
      learningRateNum -= 1
      if(learningRateNum == 0):
        print(cost)
        print("over")
        return initW , initB 

  return initW, initB


In [13]:
w = []
b = []
for i in range(10):
    print(f"run {i}")
    w1, b1 = GradientRunNew(x, 10000, 10, i)
    w.append(np.array(w1))
    b.append(np.array(b1))

run 0
Running, 0.00%, cost: 0.10010474422801285
reverse
Running, 0.05%, cost: 0.1001
reverse
Running, 0.06%, cost: 0.1001
reverse
Running, 0.07%, cost: 0.1001
reverse
Running, 0.08%, cost: 0.1001
reverse
Running, 0.09%, cost: 0.1001
reverse
Running, 0.10%, cost: 0.1001
reverse
Running, 0.11%, cost: 0.1001
reverse
Running, 0.12%, cost: 0.1001
reverse
Running, 0.13%, cost: 0.1001
reverse
Running, 0.14%, cost: 0.1001
0.1001
over
run 1
Running, 0.00%, cost: 0.11207875738461408
reverse
Running, 0.01%, cost: 0.11269241674868363
reverse
Running, 0.02%, cost: 0.11269498766915627
reverse
Running, 0.03%, cost: 0.11269519000476225
reverse
Running, 0.04%, cost: 0.1126952097742269
reverse
Running, 0.05%, cost: 0.1126952117466059
reverse
Running, 0.06%, cost: 0.11269521194379822
reverse
Running, 0.07%, cost: 0.11269521196351698
reverse
Running, 0.08%, cost: 0.11269521196548885
reverse
Running, 0.09%, cost: 0.11269521196568605
reverse
Running, 0.10%, cost: 0.11269521196570577
0.11269521196570577
over

In [16]:
from keras.datasets import mnist
import Picture.convertToData as convert
import Picture.pictureToPixel as toPix
import matplotlib.pyplot as plt
import Picture.calculateW as calc
import numpy as np
from keras.utils import to_categorical
def GetCurrentImage(num, index):
    (trainImage, trainLabel), (testImage, testLabel) = mnist.load_data()
    trainLabel = to_categorical(trainLabel)
    pixel = trainImage[num]
    pixel = convert.PixelNormalize(pixel)
    pixel = convert.ToPooling([pixel, pixel, pixel], 26)
    line = np.array(convert.ToLine(pixel[0]))
    return pixel, line, trainLabel[num][index]

def CheckAcc(line, ans, w, b):
    x = (line * w).sum() + b
    return x 

In [22]:
w = np.array(w)
wNew = w.mean(axis=0)
b = np.array(b)
bNew = b.mean()
print(bNew)
(trainImage, trainLabel), (testImage, testLabel) = mnist.load_data()
trainLabel
print(trainLabel)
print(w)
print(b)
for i in range(2000, 2100):
    list = []
    for j in range(1):
        pixel, line, ans = GetCurrentImage(i, j)
        per = (int)(CheckAcc(line, ans, w[j], b[j])*100)/100
        list.append(per)
    sorted_indices = np.argsort(list)
    print(f"List of {trainLabel[i]} result is {list}")

-4.337218389282103
[5 0 4 ... 5 6 8]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ... -3.71459695e-04
  -8.38779956e-05  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ... -1.28322440e-04
  -2.89760349e-05  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ... -6.71023965e-05
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ... -1.28322440e-04
  -2.89760349e-05  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ... -3.25925926e-04
  -8.38779956e-05  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ... -3.71459695e-04
  -8.38779956e-05  0.00000000e+00]]
[-5.49938644 -1.87318883 -5.50549754 -5.48044203 -1.90422216 -5.58371961
 -4.59284346 -1.88522216 -5.5342197  -5.51344197]
List of 5 result is [-98.03]
List of 8 result is [-111.84]
List of 8 result is [-130.98]
List of 4 result is [-71.54]
List of 2 result is [-94.2]
List of 6 result is [-76.23]
List of 9 result is [-98.46]


In [ ]:
wa1, ba1 = GradientRunNew(x, 10000, 10, 0)

In [ ]:
wa2, ba2 = GradientRunNew(x, 10000, 10, 1)

In [ ]:
wa3, ba3 = GradientRunNew(x, 10000, 10, 2)

In [ ]:
wa4, ba4 = GradientRunNew(x, 10000, 10, 3)

In [ ]:
wa5, ba5 = GradientRunNew(x, 10000, 10, 4)

In [ ]:
wa6, ba6 = GradientRunNew(x, 10000, 10, 5)

In [ ]:
wa7, ba7 = GradientRunNew(x, 10000, 10, 6)

In [ ]:
wa8, ba8 = GradientRunNew(x, 10000, 10, 7)

In [ ]:
wa9, ba9 = GradientRunNew(x, 10000, 10, 8)

In [ ]:
wa10, ba10 = GradientRunNew(x, 10000, 10, 9)

In [ ]:
w = []
b = []
w.append(np.array(wa1))
w.append(np.array(wa2))
w.append(np.array(wa3))
w.append(np.array(wa4))
w.append(np.array(wa5))
w.append(np.array(wa6))
w.append(np.array(wa7))
w.append(np.array(wa8))
w.append(np.array(wa9))
w.append(np.array(wa10))
b.append(np.array(ba1))
b.append(np.array(ba2))
b.append(np.array(ba3))
b.append(np.array(ba4))
b.append(np.array(ba5))
b.append(np.array(ba6))
b.append(np.array(ba7))
b.append(np.array(ba8))
b.append(np.array(ba9))
b.append(np.array(ba10))

In [202]:
print("hi")
w = np.array(w)
wNew = w.mean(axis=0)
b = np.array(b)
bNew = b.mean()
print(bNew)
(trainImage, trainLabel), (testImage, testLabel) = mnist.load_data()
trainLabel
print(trainLabel)
for i in range(2000, 2100):
    list = []
    for j in range(10):
        pixel, line, ans = GetCurrentImage(i, j)
        per = (int)(CheckAcc(line, ans, w[j], b[j])*100)/100
        list.append(per)
    sorted_indices = np.argsort(list)
    print(f"List of {trainLabel[i]} result is {list}")

hi
